### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Boombb** [SunnyHaze/ManTra-Net_Pytorch#2]
数据集在官网没法下载了，能提供你下载的数据集吗

**Comment by SunnyHaze** [comment]
因为涉及到版权问题，最好还是先通过官网注册账号再进行下载。

在官网网址注册账号[https://mfc.nist.gov](https://mfc.nist.gov)后再通过[OpenMFC Datasets](https://mfc.nist.gov/dataset_collections/1)进行访问。

>官网好像目前暂停了注册，请尝试联系对方的邮箱获得账号

![image](https://user-images.githubusercontent.com/62173481/164889900-4d1bc929-83bc-460a-8112-03bbd6acabee.png)
