### ISSUE TITLE
About TestModel

### ISSUE THREAD

**Issue by Boombb** [SunnyHaze/ManTra-Net_Pytorch#3]
![图片](https://user-images.githubusercontent.com/65955565/165090335-c51be452-cd5c-4891-8915-bc755e8f2bbb.png)
运行测试文件，predict feature和predict mask都是全黑，不知道哪出了问题，你有遇到过这样的情况吗？

**Comment by SunnyHaze** [comment]
我不确定您的训练参数是否和我一致，如果查看后发现每一张图都是这样，考虑可能发生了梯度爆炸的情况。

分析可能的原因：
我检查上传的代码的过程中发现了一个问题，就是我的代码learning rate貌似是1e-4，但是我在云端训练时调整为了1e-5，可能是这个原因导致的，参考的训练130epoch的训练参数：
![image](https://user-images.githubusercontent.com/62173481/165106352-51ed9a03-48e6-4cd0-9e40-2794a8d49f54.png)
（因为懒这里直接用ACC绘图，这个任务其实应该用F1指标评价，单纯用ACC评价看起来很高，但其实预测的根本不准。不过还没来得及写就被导师抓去做下一个任务了 -__-）

事实上哪怕调整好了各种训练参数，单纯在NIST16数据集中运行得到的预测结果也非常的尴尬，识别到的篡改特征基本集中在色彩强烈过度的部分，并不太能很好的反应篡改本身，比如这张没有篡改的图。
![image](https://user-images.githubusercontent.com/62173481/165107362-4fda457e-11f9-48db-83d3-8fc5c13a3e48.png)

这个仓库的目的主要是复现一下模型，感受一下原生的模型性能如何。因为如果你也读过论文应该知道，这个模型其实主要强大在Adobe那个485种操作的数据集中，它使用了非常巨量且优质的数据集喂出来的“好模型”。目前经过复现后效果不佳，说明实际上这篇论文还是强数据集造就的优异性能。
另一原因是本复现为了提高运行效率，缩放了图片，但这个压缩过程会极大地影响识别效果（论文中也提到了JPEG压缩等等会使得预测变得极为困难，主要是丢失了噪声等等重要信息），如果尝试使用1024x1024尺度的图片输入，或许会有更好的性能。

希望能解决你的问题，祝好，我一会儿修改一下learning rate。

**Comment by Boombb** [comment]
![图片](https://user-images.githubusercontent.com/65955565/165111387-80b6b919-5bae-4b26-8df9-41ab54290906.png)
我发现不同的图片通过LSTM层后好像输出的张量都是一样的
![图片](https://user-images.githubusercontent.com/65955565/165111550-f5e61f4a-73b4-4b80-99f6-70744c96ece5.png)
是这边标注的可能出现的问题吗？

**Comment by SunnyHaze** [comment]
我这里测试的训练80epoch的模型并没有如此夸张的feature map值
1.
![image](https://user-images.githubusercontent.com/62173481/165114762-e3917965-6f51-41e6-bb53-74e641e33c0d.png)
2.
![image](https://user-images.githubusercontent.com/62173481/165114895-5bb26cf0-0435-44d2-9af5-de6b1a99e4cd.png)
3.
![image](https://user-images.githubusercontent.com/62173481/165114963-3a49cce4-921c-4781-8099-30d09805742c.png)

目测可能是LSTM内部发生了梯度爆炸导致，可以考虑学习率转为1e-5重新训练，之前有印象好像**确实1e-4会导致模型难以收敛**才在云平台修改的参数。

至于这个注释，是因为当时直接引用了别人的ConvLSTM代码，当时没太分得清如何获得输出的h值或者c值，怕取错了影响结果所以写了个注释提醒自己debug，后来在其他大佬那里求证这里应该是对的。

**Comment by Boombb** [comment]
十分感谢！我明天调整一下，重新训练看看能否解决

**Comment by Boombb** [comment]
![图片](https://user-images.githubusercontent.com/65955565/165221577-7435c57d-8424-4232-950b-8cb5b24458d7.png)
修改learning rate后用CASIA数据集的部分训练了50epoch，初有成效，感谢你提出的解决方案！
打算多喂一些数据集，看看能不能获得更好的效果
也祝你在图像篡改领域的研究越来越顺利

**Comment by SunnyHaze** [comment]
祝好~ 😄

**Comment by SunnyHaze** [comment]
> ![图片](https://user-images.githubusercontent.com/65955565/165221577-7435c57d-8424-4232-950b-8cb5b24458d7.png) 修改learning rate后用CASIA数据集的部分训练了50epoch，初有成效，感谢你提出的解决方案！ 打算多喂一些数据集，看看能不能获得更好的效果 也祝你在图像篡改领域的研究越来越顺利

朋友，不知道从这里评论你是否能看见，我有点好奇你CASIA的GroundTruth是哪里来的，因为我们在做实验时发现有一个传播很广的CASIA数据集内部有20张图左右的GroundTruth是不太对的，我想确认一下我们发现的这个问题是广泛存在，还是个例，谢谢！
具体内容我已经发布到这个仓库：https://github.com/SunnyHaze/CASIA2.0-Corrected-Groundtruth
联系您主要是想佐证一下 ：）

**Comment by TsForever** [comment]
> ![图片](https://user-images.githubusercontent.com/65955565/165221577-7435c57d-8424-4232-950b-8cb5b24458d7.png) 修改learning rate后用CASIA数据集的部分训练了50epoch，初有成效，感谢你提出的解决方案！ 打算多喂一些数据集，看看能不能获得更好的效果 也祝你在图像篡改领域的研究越来越顺利

你好朋友，我最近也在复现这个项目，请问该怎么在CASIA数据集上进行训练呢？
