### ISSUE TITLE
未篡改图像的mask

### ISSUE THREAD

**Issue by Boombb** [SunnyHaze/ManTra-Net_Pytorch#4]
![图片](https://user-images.githubusercontent.com/65955565/167060116-f542d83a-f363-4eed-ac44-673cdc13b610.png)
这个是你贴出来的一个100轮测试结果
那label中未篡改区域是白色，对应值为1，篡改区域是黑色，对应值为0
那为什么生成未篡改图像的mask时使用了torch.zeros而不是torch.ones呢？
![图片](https://user-images.githubusercontent.com/65955565/167060504-5ae5e5ec-a94f-4ab7-a5c0-491b1d656cf1.png)

**Comment by SunnyHaze** [comment]
这里可能确实没注意，很有可能书写了BUG。
时间有点远我再调试一下确认是不是确实是bug，我尝试一下修改以后训练看看模型能力有没有提升。明天再回复。

如果带来了困扰，很抱歉！

**Comment by SunnyHaze** [comment]
不好意思，前两天比较忙，周末仔细检查了一下这个问题，结论是：代码是**没有问题的**，有问题的应该是我选用的样例图片。我可能选用了我早期开发时的截图作为了示例图片。后来因为解决plt.imshow()的一个[显示bug](https://www.zhihu.com/question/405249134)以及调参的过程中对所有图片的mask进行了反相处理。
![image](https://user-images.githubusercontent.com/62173481/167291152-7dbf4544-66f6-4d55-9057-98d059e7c220.png)


NIST数据集的原始mask是黑色代表篡改过，白色代表原始图片。

我的预览代码中因为直接调用了`Train.py`中的`MyDataset`，其中进行了反相处理，所以预览的图片是：黑色代表原始图片，白色代表篡改过的图片。

带来的困扰很抱歉，但是代码确实是没有问题的，我这两天修改一下README中的示例图片，以免引起进一步的困扰。

感谢您的反馈！

**Comment by SunnyHaze** [comment]
另外，对于matplotlib.pyplot中的bug，其实并没有解决的特别好，我也会更新一个解决了该bug的版本。

此bug为：
```python
a = np.ones((100,100))
plt.imshow(a, cmap='gray')
```
此时虽然是个全为1的矩阵，输出的图片却会完全呈现黑色（它认为这些1是0~255范围的1，导致全部接近黑色），影响了我前期构建代码时对于mask颜色的判断。

![image](https://user-images.githubusercontent.com/62173481/167291353-93d2149e-cb9e-45bb-9905-e2487d162a0d.png)

解决方案参考此[知乎链接](https://www.zhihu.com/question/405249134)

通过自定义标准化方式即可
![image](https://user-images.githubusercontent.com/62173481/167291379-af3984e9-02f2-45ed-bfda-4370b6cddc49.png)

**Comment by SunnyHaze** [comment]
思考了一下，其实把代码中的“反相”操作都去掉就行了...当时可能一根筋了...我还是从这个角度去修改一下代码吧，应该是不影响准确率和效果的。

**Comment by Boombb** [comment]
感谢你的回答，我发现这个点后的处理就是把反向操作去掉了

**Comment by Boombb** [comment]
十分感谢，因为不确定我的判断所以才来提问了，我对这个的处理也是直接把取反操作去掉

**Comment by SunnyHaze** [comment]
哈哈哈哈，当时主要确实被plt.imshow这个问题搞蒙了，白色的图怎么输出都是黑色的，所以折腾了很多可能出问题的地方调试，也很不好意思影响你了，抱歉抱歉。我还需要多写点代码成长成长🤣

**Comment by Boombb** [comment]
我也发现了imshow的问题，我一点点摸索才解决
![图片](https://user-images.githubusercontent.com/65955565/167304385-2b758566-f4fd-4f35-bce7-55644c96fe64.png)
我将这里的y trans之后，convert了一下
![图片](https://user-images.githubusercontent.com/65955565/167304423-f714ab59-d326-4825-a178-5a2e94657cf6.png)
就可以显示白色了
我也是在通过你的代码学习，一起努力
